---
name:   DDBX Demo                   # The application display name
short:  DDBX                        # A shortened name for reference
appid:  edu.cornell.gdiac.ddbx      # Application identifier for Mac, iOS, Android
suffix: GEABFA8D

build:  build                       # The build directory (targets are each a subdirectory)
assets: assets                      # The folder with the game assets (do not list asset)
icon:   icon.png

orientation: landscape              # The orientation for mobile devices

sources:                            # The list of the source code files
    - source/*.cpp
    - source/*.h
    
modules: all

# This is how we pull in external libraries
external:
    - name: cpr                     # The name for the entire package
      path: cpr                     # The (relative) path to the package directory
      targets:                      # A list of all libraries to link to app
          - cpr                     # This is the name in the CMake file
      options:                      # Command line options to pass to CMake
          BUILD_SHARED_LIBS: OFF

# This must be one of portrait, landscape, portrait-flipped, landscape-flipped,
targets:                            # The target platforms to build for
    - android                       # Android Studio
    - apple                         # XCode (note macOS and iOS use one project)
    - windows                       # Windows Sisual Studio
    - cmake                         # This supports all Desktop platforms
